### ISSUE TITLE
install Firefox, remove FF-ESR

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-19.08#1]

**Comment by ScarlettGatelyMoore** [comment]
I tried to achieve this over the weekend and failed - in the end it seems firefox is not available in testing or stable, only unstable.
Package 'firefox' has no installation candidate
Confirmed here:
https://wiki.debian.org/Firefox

**Comment by llelectronics** [comment]
There are two options

1. We sync the ff packages from unstable all the time to our repo. (Rebuilding FF on DCI was always problematic and is nothing I would recommend) 
2. We ommit the packaging ourselfs or syncing process by shipping a precompiled binary by mozilla directly in a folder world writeable so it can update itself there always to the newest version.

All the above have downsides and upsides. 
The first would put pressure on us to always update FF and keep track of security issues.
Benefit would be us in control of which version we ship and knowing the version our users have.
The second would always update to the newest version and so also the newest security update.
Downside is that we don't have control over the version our users have and not always know which version they might be currently running. 

One third option would be staying at FF-ESR as it is maintained by Debian for us and besides being an older release has not much downsides for us.

**Comment by star-buck** [comment]
Maybe we can try snapd and see how it goes (also on the zeroboxes though)?

**Comment by llelectronics** [comment]
I will checkout if a snap exists for armhf and arm64. So far we managed fine on the zeroboxes with ff-esr. 
If there is no particular reason I would not recommend switching to the regular Firefox.

**Comment by star-buck** [comment]
We shipped FF in blackbird.
