### ISSUE TITLE
stop building netrunner 19.01?

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-19.08#22]
is there a reason we still build it?
![Screenshot_20190727_094827](https://user-images.githubusercontent.com/840070/61991664-bb244000-b053-11e9-8820-bdf507351082.png)

**Comment by ScarlettGatelyMoore** [comment]
No - it is probably left over from when we copied files to new server. I will delete it.

**Comment by ScarlettGatelyMoore** [comment]
This is now deleted
