### ISSUE TITLE
gmuiscbrowser: gtk2 theming not fully applied

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-19.08#24]
![Screenshot_20190727_112443](https://user-images.githubusercontent.com/840070/61992629-3cce9a80-b061-11e9-890b-e36e875e0390.png)

switching to breeze dark
![Screenshot_20190727_112634](https://user-images.githubusercontent.com/840070/61992653-7acbbe80-b061-11e9-8814-a6f7b950be25.png)

and back makes it look normal again:
![Screenshot_20190727_112648](https://user-images.githubusercontent.com/840070/61992654-7d2e1880-b061-11e9-99b8-3a8a60711adf.png)

**Comment by llelectronics** [comment]
Should be fixed. The gtkrc file was including Breeze-Dark CSS stuff while using Breeze theming. Including the right Breeze css stuff fixes the issue (github autoclosed the issue as I mentioned this bug here in my commit message)
