### ISSUE TITLE
apt: now debian testing is twice there,once even activated

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-19.08#31]
![Screenshot_20190731_074936](https://user-images.githubusercontent.com/840070/62209613-19109a80-b368-11e9-9aa5-969f751c3c3a.png)

**Comment by llelectronics** [comment]
This is now how it looks like on the latest ISO (20190731.1549) 
![image](https://user-images.githubusercontent.com/3415572/62282629-299c4000-b450-11e9-95cf-baf613f7935c.png)

**Comment by star-buck** [comment]
Is nomad gone in all of the lines?

**Comment by llelectronics** [comment]
Yes nomad is gone
