### ISSUE TITLE
FF: does have sidebar visible default again

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-19.08#32]
latest RC:
![Screenshot_20190731_075003](https://user-images.githubusercontent.com/840070/62209653-2c236a80-b368-11e9-9ebe-e8b33ecd0afd.png)

**Comment by llelectronics** [comment]
Cannot reproduce on the latest image (20190731.1549)
![image](https://user-images.githubusercontent.com/3415572/62289881-2c9f2c80-b460-11e9-823c-674c3e627ecd.png)

**Comment by llelectronics** [comment]
Still not reproducable on **netrunner-20190805.0503**

**Comment by ScarlettGatelyMoore** [comment]
Still not reproducible netrunner-20190809.1635
