### ISSUE TITLE
apt: if you add "plasma" in netrunner-1908-desktop, shouldnt it be added to backports line too?

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-19.08#33]

**Comment by llelectronics** [comment]
Strange it did not end up on todays image **netrunner-20190805.0503**

**Comment by ScarlettGatelyMoore** [comment]
I removed plasma altogether as we decided against holding delta for plasma ( only way to patch is to package newer release on dci ) We will have to work with maxy to get into backports.
