### ISSUE TITLE
apt: i386 repo warnings

### ISSUE THREAD

**Issue by llelectronics** [blue-systems/netrunner-19.08#34]
![image](https://user-images.githubusercontent.com/3415572/62361299-05596580-b51b-11e9-96b1-860c14d6c30a.png)

We need to check whats going on there and maybe activate i386 repos (even if empty) for getting rid of this warnings.

**Comment by llelectronics** [comment]
Still have this issue with todays image **netrunner-20190805.0503**

**Comment by star-buck** [comment]
How to get rid of them?

**Comment by ScarlettGatelyMoore** [comment]
I am working on it. I think I found the issue. crosses fingers.

**Comment by llelectronics** [comment]
InRelease has i386. And the single repos it complains about aswell. I assume those i386 complains come from aptly not populating the i386 stuff if there is nothing in there.

**Comment by ScarlettGatelyMoore** [comment]
Turned out that even after adding the i386 arch it was updating the old publish ( which didn't have i386 ) so I removed that snapshot and it created a new one that does now have i386. Will be ready to test next ISO.

**Comment by llelectronics** [comment]
Seems fixed now.

**Comment by ScarlettGatelyMoore** [comment]
still fixed

**Comment by star-buck** [comment]
works
