### ISSUE TITLE
synaptic: after activating "testing" and refreshing, synaptic shows no packages for update. marking does nothing. clearly everwhere else, it shows hundreds of packages available for update

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-19.08#37]
activated repo:
![Screenshot_20190806_183638](https://user-images.githubusercontent.com/840070/62566883-85fcc680-b879-11e9-9515-a630eb0b6779.png)
after rescan and reload:
![Screenshot_20190806_183615](https://user-images.githubusercontent.com/840070/62566864-79786e00-b879-11e9-9c6a-811414767410.png)
apt:
![Screenshot_20190806_183650](https://user-images.githubusercontent.com/840070/62566911-93b24c00-b879-11e9-82e3-9938549ba2b1.png)
update manager:
![Screenshot_20190806_183720](https://user-images.githubusercontent.com/840070/62566922-990f9680-b879-11e9-9808-c2af29365e3f.png)

**Comment by llelectronics** [comment]
Works fine for me with the latest image **20190806.2112**
![image](https://user-images.githubusercontent.com/3415572/62613509-dde30e00-b909-11e9-91ab-d47b9642fa06.png)

**Comment by ScarlettGatelyMoore** [comment]
Confirmed that is works fine
![VirtualBox_Netrunner Desktop_09_08_2019_11_35_01](https://user-images.githubusercontent.com/1056501/62801113-dd797d00-ba99-11e9-9a8e-12bd5cffa644.png)

**Comment by star-buck** [comment]
works
