### ISSUE TITLE
Kvantum: Kvindgo2 theme: change two settings

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-19.08#38]
in config file, change the following lines:

```
no_inactiveness=true
dialog_button_layout=4
```

**Comment by llelectronics** [comment]
Had to fix a typo for it to work: https://github.com/netrunner-artwork/artwork-lnf-theme-netrunner-indigo/commit/46b089eb748a1d13fe120c092a1ba840490e023d

**Comment by ScarlettGatelyMoore** [comment]
Fixed in netrunner-20190809.1635
thank you
