### ISSUE TITLE
wallpapers: remove all blackbird, add new default one

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-19.08#4]
add this one to be new default:
https://www.dropbox.com/s/74dti65e2rnbavz/Indigo-mod-2.jpg?dl=0

**Comment by llelectronics** [comment]
Added new package here: https://github.com/netrunner-artwork/artwork-wallpapers-netrunner-1908-desktop

**Comment by ScarlettGatelyMoore** [comment]
Fixed on newest iso
