### ISSUE TITLE
adjust fonts

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-19.08#41]
adjust fonts to this for final image:

![Screenshot_20190806_193525](https://user-images.githubusercontent.com/840070/62571654-66699c00-b881-11e9-9f80-6dd921e9fc12.png)

**Comment by ScarlettGatelyMoore** [comment]
Hi, adjust what font to what font?

**Comment by ScarlettGatelyMoore** [comment]
Nevermind - I see now the picture shows what you want. On it.

**Comment by ScarlettGatelyMoore** [comment]
Done.
![Screenshot_debiantesting_2019-08-11_16:55:33](https://user-images.githubusercontent.com/1056501/62841083-dfd60580-bc58-11e9-95a5-34ad4c09d4d6.png)

**Comment by star-buck** [comment]
How does it look on your end?

**Comment by ScarlettGatelyMoore** [comment]
Sorry was eating dinner. Just updated my desktop, looks good to me :)

**Comment by star-buck** [comment]
lets reduce Window Title to 10px, same font.

**Comment by star-buck** [comment]
lets actually leave it at 11, i need to try on another machine first...

**Comment by llelectronics** [comment]
Ok I change it back :P

**Comment by star-buck** [comment]
Yeah, this computer has a weird resolutions, could be it looks different on
fullhd again.

**Comment by star-buck** [comment]
im tending to also make it ntot sans 9px regular, but let me keep on testing a bit

**Comment by star-buck** [comment]
lets set it Window title to NotoSans regular 9px then as well :)
