### ISSUE TITLE
adding new wallpapers from ghns does create black entries?

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-19.08#45]
not sure why this is on my computer:
![Screenshot_20190815_121045](https://user-images.githubusercontent.com/840070/63094253-203ec780-bf68-11e9-9bb4-30f90a68a983.png)

**Comment by ScarlettGatelyMoore** [comment]
Works ok for me.
![Screenshot_20190815_055436](https://user-images.githubusercontent.com/1056501/63095909-455c1780-bf21-11e9-88d0-71ff26ee0223.png)

**Comment by star-buck** [comment]
wow, thats a gfx issue then? that would be weird, as the other wallpapers appear fine?
i would need to check in the wallpaper folder then though
