### ISSUE TITLE
Noto: install only the basic Noto fonts

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-19.08#46]

**Comment by star-buck** [comment]
still 236 fonts here, mostly Noto:
![Screenshot_20190816_184233](https://user-images.githubusercontent.com/840070/63190393-aa188e80-c055-11e9-8f9d-c68d2b199a5c.png)

**Comment by ScarlettGatelyMoore** [comment]
Yeah I responded in telegram. They are brought in by plasma-integration it seems. I am working on a blacklisting solution.

**Comment by ScarlettGatelyMoore** [comment]
Here is the upstream culprit https://salsa.debian.org/qt-kde-team/kde/plasma-desktop/commit/d10abad4ff2cb19a632f85ca8cb8426dbd1161dc
fonts-noto is metapackage that brings in all noto fonts. The only solution I see it to manually remove each one in live-build hook. Will see what I can do.

**Comment by star-buck** [comment]
is that a good idea when its a hard-dependency in case of updates, etc?

**Comment by star-buck** [comment]
or can you apt pin it in a way its 100% reliable after installation?

**Comment by ScarlettGatelyMoore** [comment]
afaik it is only a recommends. I will test it.

**Comment by ScarlettGatelyMoore** [comment]
Good news is that reduced it down to 204 fonts, which was 2.7 -> 2.4 image size. I am however now attempting it so that the pinning happens during build time and not leaving that file after.

**Comment by star-buck** [comment]
Wow, thats pretty nice.

**Comment by ScarlettGatelyMoore** [comment]
Pinning solution didn't quite work out as the file remained post build. I was however able to reduce manually removing all noto fonts except core during build, so we are down to 2.4G and upgrades etc, will not get affected.

**Comment by star-buck** [comment]
Any link to iso for testing?

**Comment by ScarlettGatelyMoore** [comment]
A new ISO is building now, I fixed a few more of the issues. I will post in telegram when done.

**Comment by star-buck** [comment]
awesome thanks
