### ISSUE TITLE
Calamares source fails due to version too old.

### ISSUE THREAD

**Issue by ScarlettGatelyMoore** [blue-systems/netrunner-19.08#5]
I do not have access to this repo 
https://github.com/calamares/calamares-debian 
The version needs to be updated to a newer release.
09:23:21 uscan info: specified --download-debversion to set the last version: 3.2.1
09:23:21 uscan info: Download the --download-debversion specified version (dversionmangled): 3.2.1
09:23:21 uscan info: Requesting URL:
09:23:21    https://github.com/calamares/calamares/releases
09:23:21 uscan info: Matching pattern:
09:23:21    (?:(?:https://github.com)?\/calamares\/calamares\/releases)?.*/calamares-(?:[-_]?(\d[\-+\.:\~\da-zA-Z]*))(?i)(?:\.(?:tar\.xz|tar\.bz2|tar\.gz|zip|tgz|tbz|txz))
09:23:21 uscan info: Found the following matching hrefs on the web page (newest first):
09:23:21    /calamares/calamares/releases/download/v3.2.11/calamares-3.2.11.tar.gz (3.2.11) index=3.2.11-1 
09:23:21    /calamares/calamares/releases/download/v3.2.10/calamares-3.2.10.tar.gz (3.2.10) index=3.2.10-1 
09:23:21    /calamares/calamares/releases/download/v3.2.9/calamares-3.2.9.tar.gz (3.2.9) index=3.2.9-1 
09:23:21    /calamares/calamares/releases/download/v3.2.8/calamares-3.2.8.tar.gz (3.2.8) index=3.2.8-1 
09:23:21    /calamares/calamares/releases/download/v3.2.7/calamares-3.2.7.tar.gz (3.2.7) index=3.2.7-1 
09:23:21    /calamares/calamares/releases/download/v3.2.6/calamares-3.2.6.tar.gz (3.2.6) index=3.2.6-1 
09:23:21    /calamares/calamares/releases/download/v3.2.5/calamares-3.2.5.tar.gz (3.2.5) index=3.2.5-1 
09:23:21    /calamares/calamares/releases/download/v3.2.4/calamares-3.2.4.tar.gz (3.2.4) index=3.2.4-1 
09:23:21    /calamares/calamares/releases/download/v3.2.3/calamares-3.2.3.tar.gz (3.2.3) index=3.2.3-1 
09:23:21    /calamares/calamares/releases/download/v3.2.2/calamares-3.2.2.tar.gz (3.2.2) index=3.2.2-1 
09:23:21 uscan info: Scan finished

We are on 3.2.1 and latest release is 3.2.11

**Comment by llelectronics** [comment]
We use the version provided by Debian and don't package Calamares since 19.01

**Comment by ScarlettGatelyMoore** [comment]
Ah ok, I will remove from job conf file then, thanks!
